export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';


export const SAVE_BLOCK = 'SAVE_BLOCK';
export const REMOVE_BLOCK = 'REMOVE_BLOCK';
export const EDIT_BLOCK = 'EDIT_BLOCK';